name:                social-network-sim
version:             0.1.0.0
license:             BSD-3-Clause
author:              "Han Jay Tan"
maintainer:          "hanjay2003@gmail.com"
copyright:           "2026 Han Jay Tan"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/social-network-sim#readme>

dependencies:
- base >= 4.7 && < 5
- random
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

executables:
  social-network-sim-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N